### ISSUE TITLE
arm64 builds

### ISSUE THREAD

**Issue by totaam** [Xpra-org/repo-build-scripts#3]
This issue probably belongs here:
https://github.com/Xpra-org/xpra/issues/3291

**Comment by totaam** [comment]
Initial support in 71f39e4495967925a13b2358e85b107fc6ff52c8.

Tweaks:
* we need `xz` explicitly now? cbc779a903fdae917a6c2722fac3b0dfb5ca5c5b
* re-initialize images: 680812c204a04b55f35bfcc92d6c16f18e52081f + 3bb9d9ee65f9036bc7de38dfe086bf2aa0d53822

Remaining issues:
* `error while running runtime: exit status 1` - no clear solution for this one
* the builtbot crashed, possibly because of the heavy load?
* should we do parallel builds so that `x86_64` can go through quicker? (hard..)

**Comment by nakkaya** [comment]
Hi,

I the same use case as the OP in issue #3291.  I keep a web accessible emacs instance running in a docker container.  Will there be `xpra-html5` package as well ?

**Comment by totaam** [comment]
> Will there be `xpra-html5` package as well ?

@nakkaya probably.
Note: the `xpra-html5` package is already available as it is already a `noarch` package, you can grab it from the matching distribution directory for `amd64`.
(I guess it should be moved to a `noarch` repository instead)

**Comment by totaam** [comment]
Builds are in the beta area for most distributions.
The xpra 4.3 release will include arm64 builds.

**Comment by totaam** [comment]
Slight problem: I had removed `enc_ffmpeg` from the build because gcc was crashing (https://github.com/Xpra-org/xpra/commit/a416aa1762cb6292718760ecebf4a65b35242e98) and now it has crashed on the pam module whilst building the Fedora 35 arm64 images:
```
gcc -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -g -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -g -Wl,--as-needed -O2 build/temp.linux-aarch64-3.10/xpra/server/pam.o -L/usr/lib64 -o build/lib.linux-aarch64-3.10/xpra/server/pam.cpython-310-aarch64-linux-gnu.so -Wall -Wl,--as-needed -lpam -lpam_misc
error: command '/usr/bin/gcc' failed with exit code 1
error: Bad exit status from /var/tmp/rpm-tmp.JEGlIx (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.JEGlIx (%build)
error while running runtime: exit status 1
time="2021-10-03T18:06:52+07:00" level=error msg="exit status 1"
```
Unlike `ffmpeg` this one seems less reproducible and built OK on the buildbot.

Not much we can do about this.
